package environmentmanager

const (
	UPPERCASE             = "UPPERCASE"
	LOWERCASE             = "LOWERCASE"
	CAPITALIZE            = "CAPITALIZE"
	POSTGRESQL_MODEL      = "POSTGRESQL_MODEL"
	POSTGRESQL_URL_FORMAT = "POSTGRESQL_URL_FORMAT"
)

var FLAGS = []string{
	UPPERCASE,
	LOWERCASE,
	CAPITALIZE,
	POSTGRESQL_MODEL,
	POSTGRESQL_URL_FORMAT,
}
