package environmentmanager

const (
	UPPERCASE        = "UPPERCASE"
	LOWERCASE        = "LOWERCASE"
	CAPITALIZE       = "CAPITALIZE"
	POSTGRESQL_MODEL = "POSTGRESQL_MODEL"
)

var FLAGS = []string{
	UPPERCASE,
	LOWERCASE,
	CAPITALIZE,
	POSTGRESQL_MODEL,
}
